// !!! This is a file automatically generated by hipify!!!
// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT
#pragma once

#include "ck_tile/ops/reduce/block/block_reduce_hip.hpp"
#include "ck_tile/ops/reduce/block/block_reduce2d_hip.hpp"
#include "ck_tile/ops/reduce/block/block_reduce2d_problem_hip.hpp"
#include "ck_tile/ops/reduce/kernel/multi_reduce2d_kernel_hip.hpp"
#include "ck_tile/ops/reduce/kernel/multi_reduce2d_multiblock_kernel_hip.hpp"
#include "ck_tile/ops/reduce/kernel/multi_reduce2d_threadwise_kernel_hip.hpp"
#include "ck_tile/ops/reduce/kernel/multi_reduce2d_tile_partitioner_hip.hpp"
#include "ck_tile/ops/reduce/kernel/reduce2d_kernel_hip.hpp"
#include "ck_tile/ops/reduce/pipeline/reduce2d_default_policy_hip.hpp"
#include "ck_tile/ops/reduce/pipeline/reduce2d_problem_hip.hpp"
#include "ck_tile/ops/reduce/pipeline/reduce2d_shape_hip.hpp"
#include "ck_tile/ops/common/generic_2d_block_shape.hpp"
#include "ck_tile/ops/common/load_and_convert_tile_hip.hpp"
#include "ck_tile/ops/common/streamk_common_hip.hpp"
#include "ck_tile/ops/common/tensor_layout.hpp"
#include "ck_tile/ops/common/utils_hip.hpp"
