// !!! This is a file automatically generated by hipify!!!
// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

#pragma once

#include "ck_tile/core/arch/mma/sparse/mfma/selector_hip.hpp"
#include "ck_tile/core/arch/mma/sparse/wmma/selector_hip.hpp"
