// !!! This is a file automatically generated by hipify!!!
// Copyright (c) Advanced Micro Devices, Inc., or its affiliates.
// SPDX-License-Identifier: MIT

#pragma once

// Include the architecture-specific MFMA implementations and traits
#include "mfma_gfx9_hip.hpp"
#include "mfma_traits.hpp"
#include "mfma_selector_hip.hpp"
#include "mfma_transforms_hip.hpp"
